; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[teensy41_base]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = 
	-std=gnu++17
lib_extra_dirs = lib

[env:Colibri]
extends = teensy41_base
lib_deps = 
	Wire
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<Colibri.cpp>

[env:Ajolote]
extends = teensy41_base
lib_deps = 
	Wire
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<Ajolote.cpp>

[env:IRRing]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
	Wire
monitor_speed = 9600
build_src_filter = -<*> +<IRRing.cpp>

[env:communicationWithTeensy]
extends = teensy41_base
lib_deps = 
	Wire
	sparkfun/SparkFun BNO08x Cortex Based IMU@^1.0.6
	adafruit/Adafruit BNO08x@^1.2.5
monitor_speed = 115200
build_src_filter = -<*> +<tests/communicationWithTeensy.cpp>

[env:BNOtest]
extends = teensy41_base
monitor_speed = 9600
lib_deps = 
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/BNOReadings.cpp>

[env:I2CScan]
extends = teensy41_base
build_src_filter = -<arduino.cpp> -<tests/*> +<tests/I2CScan.cpp>
lib_deps = 
	sparkfun/SparkFun BNO08x Cortex Based IMU@^1.0.6
	adafruit/Adafruit BNO08x@^1.2.5

[env:individualMotors]
extends = teensy41_base
lib_deps = 
	Wire
	sparkfun/SparkFun BNO08x Cortex Based IMU@^1.0.6
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/individualMotors.cpp>

[env:driveDirectionCheck]
extends = teensy41_base
build_src_filter = -<*> +<tests/driveDirectionCheck.cpp>

[env:motorsSquare]
extends = teensy41_base
lib_deps = 
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/motorsSquare.cpp>

[env:getBallAngle]
extends = teensy41_base
build_src_filter = -<*> +<tests/getBallAngle.cpp>
lib_deps = 
	sparkfun/SparkFun BNO08x Cortex Based IMU@^1.0.6
	adafruit/Adafruit BNO08x@^1.2.5

[env:PIDLookForBall]
extends = teensy41_base
lib_deps = 
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/PIDLookForBall.cpp>

[env:LookForBallIROnly]
extends = teensy41_base
lib_deps = 
	Wire
build_src_filter = -<*> +<tests/LookForBallIROnly.cpp>

[env:PixyTest]
extends = teensy41_base
lib_compat_mode = soft
lib_deps = 
	arduino12/pixy2 @ ^1.0.4
	sparkfun/SparkFun BNO08x Cortex Based IMU@^1.0.6
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/PixyTest.cpp>

[env:getBallAngleWithPixy]
extends = teensy41_base
lib_compat_mode = soft
lib_deps = 
	adafruit/Adafruit BusIO
	Wire
	SPI
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/getBallAngleWithPixy.cpp>

[env:PIDLookForBallWithPixy]
extends = teensy41_base
lib_compat_mode = soft
lib_deps = 
	adafruit/Adafruit BusIO
	Wire
	SPI
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/PIDLookForBallWithPixy.cpp>

[env:PIDStickIntoOneDirection2]
extends = teensy41_base
lib_deps = 
	Wire
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/PIDStickIntoOneDirection2.cpp>

[env:GoalAimHeadingCalibration]
extends = teensy41_base
lib_compat_mode = soft
lib_deps = 
	Wire
	SPI
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/GoalAimHeadingCalibration.cpp>

[env:IMUtest]
extends = teensy41_base
lib_deps = 
	Wire
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/IMUtest.cpp>

[env:straightLineReaction]
extends = teensy41_base
lib_deps = 
	Wire
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/straightLineReaction.cpp>

[env:avoidLine]
extends = teensy41_base
lib_deps = 
	Wire
	adafruit/Adafruit BNO08x@^1.2.5
build_src_filter = -<*> +<tests/avoidLineWithPhotos.cpp>

[env:avoidLineWithPhotos]
extends = env:avoidLine
lib_deps = adafruit/Adafruit BNO08x@^1.2.5

[env:teensy41_mux_test]
extends = teensy41_base
build_src_filter = -<*> +<tests/Multiplexer_Readings.cpp>
lib_deps = adafruit/Adafruit BNO08x@^1.2.5

[env:photo_calibration]
extends = teensy41_base
build_src_filter = -<*> +<tests/PhotoCalibration.cpp>
lib_deps = adafruit/Adafruit BNO08x@^1.2.5

[env:blink]
extends = teensy41_base
build_src_filter = -<*> +<tests/blink.cpp>
lib_deps = adafruit/Adafruit BNO08x@^1.2.5

[env:IRRingReadTest]
extends = teensy41_base
build_src_filter = -<*> +<tests/IRRingReadTest.cpp>
lib_deps = 
	Wire