; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BNO055 @ ^1.5.0
	arduino12/pixy2@^1.0.4
build_src_filter = +<arduino.cpp> -<tests/**>

[env:BNOReadings]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BNO055 @ ^1.5.0
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/BNOReadings.cpp>

[env:I2CScan]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<tests/I2CScan.cBnpp>
lib_deps = arduino12/pixy2@^1.0.4

[env:individualMotors]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_speed = 115200
lib_deps = 
	ArduinoSTL
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/individualMotors.cpp>

[env:motorsSquare]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/motorsSquare.cpp>

[env:PIDStickIntoOneDirection]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BNO055 @ ^1.5.0
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/PIDStickIntoOneDirection.cpp>

[env:getBallAngle]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/getBallAngle.cpp>

[env:PIDLookForBall]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BNO055 @ ^1.5.0
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/PIDLookForBall.cpp>

[env:Multiplexer_Readings]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/Multiplexer_Readings.cpp>

[env:Single_Mux_test]
monitor_speed = 115200
platform = atmelavr
board = uno //leave this as uno for test purposes when trying a single phototransistor board
framework = arduino
lib_deps = 
	ArduinoSTL
	Wire
	adafruit/Adafruit Unified Sensor
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/Single_Multiplexer_test.cpp>

[env:PIDTestWithMUX]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	Wire
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BNO055 @ ^1.5.0
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/PIDTestWithMUX.cpp>

[env:Photo_avoid_line]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	arduino12/pixy2@^1.0.4
build_src_filter = -<*> +<tests/Photo_avoid_line.cpp>

[env:PixyTest]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_compat_mode = soft 
lib_deps = 
	ArduinoSTL
	Wire
	SPI
	adafruit/Adafruit Unified Sensor @ ^1.1.15
lib_extra_dirs = lib
build_src_filter = -<*> +<tests/PixyTest.cpp>

[env:Photo_Calibration]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	Wire
	adafruit/Adafruit Unified Sensor
build_src_filter = -<*> +<tests/Photo_Calibration.cpp>
	
[env:avoidLine]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	Wire
	adafruit/Adafruit Unified Sensor
build_src_filter = -<*> +<tests/avoidLine.cpp>

[env:avoidLine_with_vision]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	ArduinoSTL
	Wire
	SPI
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/Adafruit BNO055 @ ^1.5.0
	charmedlabs/Pixy2 @ ^3.0.6
build_src_filter = -<*> +<tests/avoidLine_with_vision.cpp>